package com.bustleandflurry.systemd.journal;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Union;
/**
 * <i>native declaration : /usr/include/systemd/sd-id128.h:35</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Union 
@Library("systemd-journal") 
public class sd_id128 extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : uint8_t[16] */
	@Array({16}) 
	@Field(0) 
	public Pointer<Byte > bytes() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : uint64_t[2] */
	@Array({2}) 
	@Field(1) 
	public Pointer<Long > qwords() {
		return this.io.getPointerField(this, 1);
	}
	public sd_id128() {
		super();
	}
	public sd_id128(Pointer pointer) {
		super(pointer);
	}
}
